version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./cfg/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./cfg/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=redis-datasource
    volumes:
      - grafana-data:/var/lib/grafana
  
  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes: 
      - redis:/data
      - ./cfg/redis-entrypoint.sh:/usr/local/bin/entrypoint.sh 
    entrypoint: ["/usr/local/bin/entrypoint.sh"]

volumes:
  loki-data:
  grafana-data:
  redis:
      driver: local   
